# Generated by Django 3.1.4 on 2020-12-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Samplepeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='名前')),
                ('kana', models.CharField(max_length=8, verbose_name='かな')),
                ('date_of_birth', models.DateField(verbose_name='生年月日')),
            ],
        ),
    ]
